//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialChartExplorer.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialChartExplorer.Localization.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Description.
        /// </summary>
        public static string ControlLayout_Description {
            get {
                return ResourceManager.GetString("ControlLayout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Documentation.
        /// </summary>
        public static string ControlLayout_Documentation {
            get {
                return ResourceManager.GetString("ControlLayout_Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Features.
        /// </summary>
        public static string ControlLayout_Features {
            get {
                return ResourceManager.GetString("ControlLayout_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sample.
        /// </summary>
        public static string ControlLayout_Sample {
            get {
                return ResourceManager.GetString("ControlLayout_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Settings.
        /// </summary>
        public static string ControlLayout_Settings {
            get {
                return ResourceManager.GetString("ControlLayout_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Source.
        /// </summary>
        public static string ControlLayout_Source {
            get {
                return ResourceManager.GetString("ControlLayout_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Features.
        /// </summary>
        public static string ControlsNav_Features {
            get {
                return ResourceManager.GetString("ControlsNav_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        public static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ComponentOne.
        /// </summary>
        public static string Layout_ComponentOne {
            get {
                return ResourceManager.GetString("Layout_ComponentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MESCIUS inc. All rights reserved.&lt;br /&gt;
        ///            All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        public static string Layout_CopyrightInfo {
            get {
                return ResourceManager.GetString("Layout_CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to http://developer.mescius.com/.
        /// </summary>
        public static string Layout_LinkCompany {
            get {
                return ResourceManager.GetString("Layout_LinkCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/aspnet-mvc.
        /// </summary>
        public static string Layout_LinkProduct {
            get {
                return ResourceManager.GetString("Layout_LinkProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ASP.NET MVC Edition FinancialChart Explorer.
        /// </summary>
        public static string Layout_TitleLong {
            get {
                return ResourceManager.GetString("Layout_TitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MVC FinancialChart Explorer.
        /// </summary>
        public static string Layout_TitleShort {
            get {
                return ResourceManager.GetString("Layout_TitleShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Have you seen this? C1Studio MVC Edition Controls.
        /// </summary>
        public static string Layout_TwitterTxt {
            get {
                return ResourceManager.GetString("Layout_TwitterTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to About.
        /// </summary>
        public static string SiteNav_About {
            get {
                return ResourceManager.GetString("SiteNav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Download.
        /// </summary>
        public static string SiteNav_FreeTrial {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/aspnet-mvc.
        /// </summary>
        public static string SiteNav_LinkAbout {
            get {
                return ResourceManager.GetString("SiteNav_LinkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/download/componentone-studio.
        /// </summary>
        public static string SiteNav_LinkFreeTrial {
            get {
                return ResourceManager.GetString("SiteNav_LinkFreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/pricing.
        /// </summary>
        public static string SiteNav_LinkPricing {
            get {
                return ResourceManager.GetString("SiteNav_LinkPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/my-account/my-support.
        /// </summary>
        public static string SiteNav_LinkSupport {
            get {
                return ResourceManager.GetString("SiteNav_LinkSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pricing.
        /// </summary>
        public static string SiteNav_Pricing {
            get {
                return ResourceManager.GetString("SiteNav_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Support.
        /// </summary>
        public static string SiteNav_Support {
            get {
                return ResourceManager.GetString("SiteNav_Support", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Demos.
        /// </summary>
        public static string SiteNav_Demos {
            get {
                return ResourceManager.GetString("SiteNav_Demos", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/componentone/demos.
        /// </summary>
        public static string SiteNav_DemosUrl {
            get {
                return ResourceManager.GetString("SiteNav_DemosUrl", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Docs.
        /// </summary>
        public static string SiteNav_Docs {
            get {
                return ResourceManager.GetString("SiteNav_Docs", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/componentone/docs/mvc/online-mvc-core/overview.html.
        /// </summary>
        public static string SiteNav_DocsUrl {
            get {
                return ResourceManager.GetString("SiteNav_DocsUrl", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Samples.
        /// </summary>
        public static string SiteNav_Samples {
            get {
                return ResourceManager.GetString("SiteNav_Samples", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/componentone/samples.
        /// </summary>
        public static string SiteNav_SamplesUrl {
            get {
                return ResourceManager.GetString("SiteNav_SamplesUrl", resourceCulture);
            }
        }

    }
}
