//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/aspnet-mvc.
        /// </summary>
        internal static string ComponentOneLink {
            get {
                return ResourceManager.GetString("ComponentOneLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        internal static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string HomeBackgroundColor {
            get {
                return ResourceManager.GetString("HomeBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string HomeBorder {
            get {
                return ResourceManager.GetString("HomeBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string HomeCalendar {
            get {
                return ResourceManager.GetString("HomeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string HomeContent {
            get {
                return ResourceManager.GetString("HomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner Radius.
        /// </summary>
        internal static string HomeCornerRadius {
            get {
                return ResourceManager.GetString("HomeCornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string HomeCountry {
            get {
                return ResourceManager.GetString("HomeCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        internal static string HomeCss {
            get {
                return ResourceManager.GetString("HomeCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string HomeDownloads {
            get {
                return ResourceManager.GetString("HomeDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string HomeExpenses {
            get {
                return ResourceManager.GetString("HomeExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexGrid.
        /// </summary>
        internal static string HomeFlexGrid {
            get {
                return ResourceManager.GetString("HomeFlexGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string HomeHeaders {
            get {
                return ResourceManager.GetString("HomeHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string HomePreview {
            get {
                return ResourceManager.GetString("HomePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string HomeSales {
            get {
                return ResourceManager.GetString("HomeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string HomeSelection {
            get {
                return ResourceManager.GetString("HomeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample helps you create custom ComponentOne MVC themes..
        /// </summary>
        internal static string HomeText1 {
            get {
                return ResourceManager.GetString("HomeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the color pickers to build a theme. Then copy the CSS into your project as a new custom theme!.
        /// </summary>
        internal static string HomeText2 {
            get {
                return ResourceManager.GetString("HomeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to add this CSS after ComponentOne MVC styles to ensure it overrides the default theme. We recommend placing this CSS in a separate file..
        /// </summary>
        internal static string HomeText3 {
            get {
                return ResourceManager.GetString("HomeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is how a tooltip looks using your custom theme.&lt;br /&gt;
        ///                    We suggest using a subtle background color..
        /// </summary>
        internal static string HomeText4 {
            get {
                return ResourceManager.GetString("HomeText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over me to see a Tooltip!.
        /// </summary>
        internal static string HomeText5 {
            get {
                return ResourceManager.GetString("HomeText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string HomeTextColor {
            get {
                return ResourceManager.GetString("HomeTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Designer.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip.
        /// </summary>
        internal static string HomeTooltip {
            get {
                return ResourceManager.GetString("HomeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentOne MVC Theme Designer.
        /// </summary>
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Designer.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SiteError {
            get {
                return ResourceManager.GetString("SiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string SiteErrorDescription {
            get {
                return ResourceManager.GetString("SiteErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESCIUS inc. All rights reserved.
        /// </summary>
        internal static string SiteFooter1 {
            get {
                return ResourceManager.GetString("SiteFooter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        internal static string SiteFooter2 {
            get {
                return ResourceManager.GetString("SiteFooter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SiteNavAbout {
            get {
                return ResourceManager.GetString("SiteNavAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/aspnet-mvc-ui-controls.
        /// </summary>
        internal static string SiteNavAboutLink {
            get {
                return ResourceManager.GetString("SiteNavAboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string SiteNavFreeTrial {
            get {
                return ResourceManager.GetString("SiteNavFreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/download.
        /// </summary>
        internal static string SiteNavFreeTrialLink {
            get {
                return ResourceManager.GetString("SiteNavFreeTrialLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string SiteNavPricing {
            get {
                return ResourceManager.GetString("SiteNavPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/pricing.
        /// </summary>
        internal static string SiteNavPricingLink {
            get {
                return ResourceManager.GetString("SiteNavPricingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string SiteNavSupport {
            get {
                return ResourceManager.GetString("SiteNavSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/my-account/my-support.
        /// </summary>
        internal static string SiteNavSupportLink {
            get {
                return ResourceManager.GetString("SiteNavSupportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demos.
        /// </summary>
        internal static string SiteNav_Demos {
            get {
                return ResourceManager.GetString("SiteNav_Demos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/demos.
        /// </summary>
        internal static string SiteNav_DemosUrl {
            get {
                return ResourceManager.GetString("SiteNav_DemosUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        internal static string SiteNav_Docs {
            get {
                return ResourceManager.GetString("SiteNav_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/docs/mvc/online-mvc/overview.html.
        /// </summary>
        internal static string SiteNav_DocsUrl {
            get {
                return ResourceManager.GetString("SiteNav_DocsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        internal static string SiteNav_Samples {
            get {
                return ResourceManager.GetString("SiteNav_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/demos.
        /// </summary>
        internal static string SiteNav_SamplesUrl {
            get {
                return ResourceManager.GetString("SiteNav_SamplesUrl", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to ComponentOne.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
    }
}
