//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransposedMultiRowExplorer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransposedMultiRowExplorer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TransposedMultiRowExplorer", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error..
        /// </summary>
        internal static string Error_Text0 {
            get {
                return ResourceManager.GetString("Error_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string Error_Text1 {
            get {
                return ResourceManager.GetString("Error_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        internal static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional grid view, with one row per record.The user must scroll horizontally to see the whole record..
        /// </summary>
        internal static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view uses two rows per record. The layout is divided into three groups: order, customer, and shipper..
        /// </summary>
        internal static string Index_Text1 {
            get {
                return ResourceManager.GetString("Index_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view uses three rows per record. The layout is divided into three groups: order, customer, and shipper..
        /// </summary>
        internal static string Index_Text2 {
            get {
                return ResourceManager.GetString("Index_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TransposedMultiRow control extends Grid control to display data using a transposed layout, where columns represent data items and rows represent item properties. Also this control allows to display each item in multiple columns..
        /// </summary>
        internal static string Index_Text3 {
            get {
                return ResourceManager.GetString("Index_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;TransposedMultiRow&lt;/b&gt; control extends Grid control to display data using a transposed layout, where columns represent data items and rows represent item properties. Also this control allows to display each item in multiple columns..
        /// </summary>
        internal static string Index_Text4 {
            get {
                return ResourceManager.GetString("Index_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string _ControlLayout_Text0 {
            get {
                return ResourceManager.GetString("_ControlLayout_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string _ControlLayout_Text1 {
            get {
                return ResourceManager.GetString("_ControlLayout_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        internal static string _ControlLayout_Text2 {
            get {
                return ResourceManager.GetString("_ControlLayout_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string _ControlLayout_Text3 {
            get {
                return ResourceManager.GetString("_ControlLayout_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _ControlLayout_Text4 {
            get {
                return ResourceManager.GetString("_ControlLayout_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string _ControlsNav_Text0 {
            get {
                return ResourceManager.GetString("_ControlsNav_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrapeCity, Inc. All Rights Reserved.&lt;br /&gt;&lt;/br&gt;All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        internal static string _Layout_Text0 {
            get {
                return ResourceManager.GetString("_Layout_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentOne.
        /// </summary>
        internal static string _Layout_Text1 {
            get {
                return ResourceManager.GetString("_Layout_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVC TransposedMultiRow Explorer.
        /// </summary>
        internal static string _Layout_Text2 {
            get {
                return ResourceManager.GetString("_Layout_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC Edition TransposedMultiRow Explorer.
        /// </summary>
        internal static string _Layout_Text3 {
            get {
                return ResourceManager.GetString("_Layout_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/en/aspnet-mvc.
        /// </summary>
        internal static string _Layout_Text4 {
            get {
                return ResourceManager.GetString("_Layout_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1 ASP.NET MVC.
        /// </summary>
        internal static string _Layout_Text5 {
            get {
                return ResourceManager.GetString("_Layout_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string _SiteNav_Text0 {
            get {
                return ResourceManager.GetString("_SiteNav_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string _SiteNav_Text1 {
            get {
                return ResourceManager.GetString("_SiteNav_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string _SiteNav_Text2 {
            get {
                return ResourceManager.GetString("_SiteNav_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE TRIAL.
        /// </summary>
        internal static string _SiteNav_Text3 {
            get {
                return ResourceManager.GetString("_SiteNav_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Theme &amp;gt;.
        /// </summary>
        internal static string _SiteNav_Text4 {
            get {
                return ResourceManager.GetString("_SiteNav_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/componentone/aspnet-mvc-ui-controls.
        /// </summary>
        internal static string _SiteNav_Text5 {
            get {
                return ResourceManager.GetString("_SiteNav_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/my-account/my-support.
        /// </summary>
        internal static string _SiteNav_Text6 {
            get {
                return ResourceManager.GetString("_SiteNav_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/componentone/pricing.
        /// </summary>
        internal static string _SiteNav_Text7 {
            get {
                return ResourceManager.GetString("_SiteNav_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/componentone/download.
        /// </summary>
        internal static string _SiteNav_Text8 {
            get {
                return ResourceManager.GetString("_SiteNav_Text8", resourceCulture);
            }
        }
    }
}
