//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Calendar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calendar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Calendar", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/aspnet-mvc.
        /// </summary>
        internal static string ComponentOneLink {
            get {
                return ResourceManager.GetString("ComponentOneLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1 MVC version of the Slack status page. See the original &lt;a href=&quot;https://status.slack.com/calendar&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt;..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity Issues,ISP Reported Problem,Message Server Overflow,Security Alert,Email Failure,Power Instability,Power Outage.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        internal static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        internal static string Incident {
            get {
                return ResourceManager.GetString("Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        internal static string Maintenance {
            get {
                return ResourceManager.GetString("Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No incidents, outages, or maintenance..
        /// </summary>
        internal static string NoEvent {
            get {
                return ResourceManager.GetString("NoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outage.
        /// </summary>
        internal static string Outage {
            get {
                return ResourceManager.GetString("Outage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a custom Calendar.
        /// </summary>
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SiteError {
            get {
                return ResourceManager.GetString("SiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string SiteErrorDescription {
            get {
                return ResourceManager.GetString("SiteErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESCIUS inc. All rights reserved..
        /// </summary>
        internal static string SiteFooter1 {
            get {
                return ResourceManager.GetString("SiteFooter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        internal static string SiteFooter2 {
            get {
                return ResourceManager.GetString("SiteFooter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SiteNavAbout {
            get {
                return ResourceManager.GetString("SiteNavAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/aspnet-mvc-ui-controls.
        /// </summary>
        internal static string SiteNavAboutLink {
            get {
                return ResourceManager.GetString("SiteNavAboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string SiteNavFreeTrial {
            get {
                return ResourceManager.GetString("SiteNavFreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/download.
        /// </summary>
        internal static string SiteNavFreeTrialLink {
            get {
                return ResourceManager.GetString("SiteNavFreeTrialLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string SiteNavPricing {
            get {
                return ResourceManager.GetString("SiteNavPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/pricing.
        /// </summary>
        internal static string SiteNavPricingLink {
            get {
                return ResourceManager.GetString("SiteNavPricingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string SiteNavSupport {
            get {
                return ResourceManager.GetString("SiteNavSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/my-account/my-support.
        /// </summary>
        internal static string SiteNavSupportLink {
            get {
                return ResourceManager.GetString("SiteNavSupportLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Demos.
        /// </summary>
        internal static string _SiteNav_Demos {
            get {
                return ResourceManager.GetString("_SiteNav_Demos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/demos.
        /// </summary>
        internal static string _SiteNav_DemosUrl {
            get {
                return ResourceManager.GetString("_SiteNav_DemosUrl", resourceCulture);
            }
        }        

        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        internal static string _SiteNav_Docs {
            get {
                return ResourceManager.GetString("_SiteNav_Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/docs/mvc/online-mvc/overview.html.
        /// </summary>
        internal static string _SiteNav_DocsUrl {
            get {
                return ResourceManager.GetString("_SiteNav_DocsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        internal static string _SiteNav_Samples {
            get {
                return ResourceManager.GetString("_SiteNav_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.mescius.com/componentone/samples.
        /// </summary>
        internal static string _SiteNav_SamplesUrl {
            get {
                return ResourceManager.GetString("_SiteNav_SamplesUrl", resourceCulture);
            }
        }
                
        /// <summary>
        ///   Looks up a localized string similar to ComponentOne.
        /// </summary>
        internal static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
