//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        internal static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example shows a table with financial data. The data contains two column groups, one showing fund performance and one showing fund composition..
        /// </summary>
        internal static string Index_View_Financial_P1 {
            get {
                return ResourceManager.GetString("Index_View_Financial_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grids below have hierarchical column structures where some columns contain groups of columns..
        /// </summary>
        internal static string Index_View_P1 {
            get {
                return ResourceManager.GetString("Index_View_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The columns have multi-level, merged headers that reflect the structure of the data. Clicking header cells selects the whole group..
        /// </summary>
        internal static string Index_View_P2 {
            get {
                return ResourceManager.GetString("Index_View_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both examples create the headers using the &lt;b&gt;ColumnGroupProvider&lt;/b&gt; class which is defined in the &lt;b&gt;wijmo.grid.columngroups&lt;/b&gt; extension module..
        /// </summary>
        internal static string Index_View_P3 {
            get {
                return ResourceManager.GetString("Index_View_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example is based on the &lt;a href=&quot;http://www.w3.org/TR/html401/struct/tables.html&quot;&gt;W3 page that describes the table element&lt;/a&gt;. It shows a simple table with a column group that shows &quot;Average&quot; weight and height values:.
        /// </summary>
        internal static string Index_View_W3C_P1 {
            get {
                return ResourceManager.GetString("Index_View_W3C_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentOne.
        /// </summary>
        internal static string Layout_ComponentOne {
            get {
                return ResourceManager.GetString("Layout_ComponentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.grapecity.com/.
        /// </summary>
        internal static string Layout_GrapeCityUrl {
            get {
                return ResourceManager.GetString("Layout_GrapeCityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrapeCity, Inc. All Rights Reserved..
        /// </summary>
        internal static string Layout_License1 {
            get {
                return ResourceManager.GetString("Layout_License1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        internal static string Layout_License2 {
            get {
                return ResourceManager.GetString("Layout_License2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC FlexGrid Column Groups.
        /// </summary>
        internal static string Layout_LongTitle {
            get {
                return ResourceManager.GetString("Layout_LongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/en/aspnet-mvc.
        /// </summary>
        internal static string Layout_ProductUrl {
            get {
                return ResourceManager.GetString("Layout_ProductUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVC FlexGrid Column Groups.
        /// </summary>
        internal static string Layout_ShortTitle {
            get {
                return ResourceManager.GetString("Layout_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - C1 ASP.NET MVC.
        /// </summary>
        internal static string Layout_TitleSuffix {
            get {
                return ResourceManager.GetString("Layout_TitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you seen this? C1Studio MVC Edition Controls.
        /// </summary>
        internal static string Layout_TwitterText {
            get {
                return ResourceManager.GetString("Layout_TwitterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial table example.
        /// </summary>
        internal static string SectionTitle_Financial {
            get {
                return ResourceManager.GetString("SectionTitle_Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3C table example.
        /// </summary>
        internal static string SectionTitle_W3C {
            get {
                return ResourceManager.GetString("SectionTitle_W3C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SiteNav_About {
            get {
                return ResourceManager.GetString("SiteNav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/componentone/aspnet-mvc-ui-controls.
        /// </summary>
        internal static string SiteNav_AboutUrl {
            get {
                return ResourceManager.GetString("SiteNav_AboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE TRIAL.
        /// </summary>
        internal static string SiteNav_FreeTrial {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/componentone/download.
        /// </summary>
        internal static string SiteNav_FreeTrialUrl {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrialUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string SiteNav_Home {
            get {
                return ResourceManager.GetString("SiteNav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        internal static string SiteNav_Pricing {
            get {
                return ResourceManager.GetString("SiteNav_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/componentone/pricing.
        /// </summary>
        internal static string SiteNav_PricingUrl {
            get {
                return ResourceManager.GetString("SiteNav_PricingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string SiteNav_Support {
            get {
                return ResourceManager.GetString("SiteNav_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.grapecity.com/my-account/my-support.
        /// </summary>
        internal static string SiteNav_SupportUrl {
            get {
                return ResourceManager.GetString("SiteNav_SupportUrl", resourceCulture);
            }
        }
    }
}
