//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExplorer.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InputNumberRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal InputNumberRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcExplorer.Localization.InputNumberRes", typeof(InputNumberRes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows the usages of the editor templates offered by C1..
        /// </summary>
        public static string EditorTemplates_Text0 {
            get {
                return ResourceManager.GetString("EditorTemplates_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use these templates out of the box with C1 MVC project template..
        /// </summary>
        public static string EditorTemplates_Text1 {
            get {
                return ResourceManager.GetString("EditorTemplates_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use EditorTemplates (with C1 MVC project template).
        /// </summary>
        public static string EditorTemplates_Text2 {
            get {
                return ResourceManager.GetString("EditorTemplates_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerOrder updated successfully, thanks!.
        /// </summary>
        public static string Form_Message {
            get {
                return ResourceManager.GetString("Form_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Form_Submit {
            get {
                return ResourceManager.GetString("Form_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to use input controls in a form..
        /// </summary>
        public static string Form_Text0 {
            get {
                return ResourceManager.GetString("Form_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also use model binding features at the same time..
        /// </summary>
        public static string Form_Text1 {
            get {
                return ResourceManager.GetString("Form_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When HandleWheel is &lt;b&gt;true&lt;/b&gt;, the user can edit the value using the mouse wheel..
        /// </summary>
        public static string HandleWheelDescription_Text0 {
            get {
                return ResourceManager.GetString("HandleWheelDescription_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number....
        /// </summary>
        public static string Index_EnterANumber {
            get {
                return ResourceManager.GetString("Index_EnterANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound with &quot;n0&quot; format.
        /// </summary>
        public static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound with &quot;n&quot; format.
        /// </summary>
        public static string Index_Text1 {
            get {
                return ResourceManager.GetString("Index_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound with Min(0), Max(10), Step, and &quot;c2&quot; Format.
        /// </summary>
        public static string Index_Text2 {
            get {
                return ResourceManager.GetString("Index_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound with placeholder and IsRequired=&quot;false&quot;.
        /// </summary>
        public static string Index_Text3 {
            get {
                return ResourceManager.GetString("Index_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows the basic usage of the InputNumber control..
        /// </summary>
        public static string Index_Text4 {
            get {
                return ResourceManager.GetString("Index_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing numeric keyboard using &lt;i&gt;InputType&lt;/i&gt; property (on mobile, tablet, iPad only).
        /// </summary>
        public static string Index_Text5 {
            get {
                return ResourceManager.GetString("Index_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In advanced, you can also use along with &lt;b&gt;InputType&lt;/b&gt; property for more masks as well as showing appropriate soft keyboard type on mobile phone, tablet, iPad etc..
        /// </summary>
        public static string Index_Text6 {
            get {
                return ResourceManager.GetString("Index_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min (100), Max (1000), check invalid number using InvalidInput event.
        /// </summary>
        public static string Index_Text7 {
            get {
                return ResourceManager.GetString("Index_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input, the value must be between 100 and 1000..
        /// </summary>
        public static string Index_Text8 {
            get {
                return ResourceManager.GetString("Index_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows how to use model binding features with input controls..
        /// </summary>
        public static string ModelBinding_Text0 {
            get {
                return ResourceManager.GetString("ModelBinding_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use for attribute in C1 input control tag..
        /// </summary>
        public static string ModelBinding_Text1 {
            get {
                return ResourceManager.GetString("ModelBinding_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use model binding.
        /// </summary>
        public static string ModelBinding_Text3 {
            get {
                return ResourceManager.GetString("ModelBinding_Text3", resourceCulture);
            }
        }
    }
}
