//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExplorer.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LinearGaugeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal LinearGaugeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcExplorer.Localization.LinearGaugeRes", typeof(LinearGaugeRes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to use the direction properties with the LinearGauge controls..
        /// </summary>
        public static string Direction_Text0 {
            get {
                return ResourceManager.GetString("Direction_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to use the IsReadOnly and Step properties with the LinearGauge controls..
        /// </summary>
        public static string Editing_Text0 {
            get {
                return ResourceManager.GetString("Editing_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;ShowTicks:&lt;/b&gt; determines whether the gauge should display tickmarks at each step or tickSpacing value..
        /// </summary>
        public static string Editing_Text1 {
            get {
                return ResourceManager.GetString("Editing_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;ShowTickText:&lt;/b&gt; determines whether the gauge should display the text value of each tick mark..
        /// </summary>
        public static string Editing_Text2 {
            get {
                return ResourceManager.GetString("Editing_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;HandleWheel:&lt;/b&gt; determines whether the user can edit the gauge value using the mouse wheel..
        /// </summary>
        public static string Editing_Text3 {
            get {
                return ResourceManager.GetString("Editing_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows the basic usage of the LinearGauge control..
        /// </summary>
        public static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The example demonstrates how to use ranges with the LinearGauge..
        /// </summary>
        public static string Ranges_Text0 {
            get {
                return ResourceManager.GetString("Ranges_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CSS.
        /// </summary>
        public static string Scaling_CustomCSS {
            get {
                return ResourceManager.GetString("Scaling_CustomCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Styles.
        /// </summary>
        public static string Scaling_DefaultStyles {
            get {
                return ResourceManager.GetString("Scaling_DefaultStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the gauges to change the color:.
        /// </summary>
        public static string Scaling_Text0 {
            get {
                return ResourceManager.GetString("Scaling_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value bound to the gauges:.
        /// </summary>
        public static string Scaling_Text1 {
            get {
                return ResourceManager.GetString("Scaling_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to scale LinearGauge controls..
        /// </summary>
        public static string Scaling_Text2 {
            get {
                return ResourceManager.GetString("Scaling_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to use the ShowText properties with the LinearGauge controls..
        /// </summary>
        public static string ShowText_Text0 {
            get {
                return ResourceManager.GetString("ShowText_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this example, we added the &quot;custom-gauge&quot; CSS class to the LinearGauge, and define some CSS rules to create an orange pointer for both..
        /// </summary>
        public static string Styling_Text0 {
            get {
                return ResourceManager.GetString("Styling_Text0", resourceCulture);
            }
        }
    }
}
