//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExplorer.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ValidationRes() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvcExplorer.Localization.ValidationRes", typeof(ValidationRes).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Register_CreateAnAccount {
            get {
                return ResourceManager.GetString("Register_CreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Email field is not a valid e-mail address..
        /// </summary>
        public static string Register_Email_ErrorMessage {
            get {
                return ResourceManager.GetString("Register_Email_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The username must be alphanumeric and contains 4 to 10 characters..
        /// </summary>
        public static string Register_Name_ErrorMessage {
            get {
                return ResourceManager.GetString("Register_Name_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Register {
            get {
                return ResourceManager.GetString("Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registration Complete.
        /// </summary>
        public static string Register_RegistrationComplete {
            get {
                return ResourceManager.GetString("Register_RegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Congratulations to.
        /// </summary>
        public static string Register_Text0 {
            get {
                return ResourceManager.GetString("Register_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ! Your registration has been successfuly submitted..
        /// </summary>
        public static string Register_Text1 {
            get {
                return ResourceManager.GetString("Register_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This sample shows the basic usage of the unobtrusive validation..
        /// </summary>
        public static string Register_Text2 {
            get {
                return ResourceManager.GetString("Register_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Press SPACE key to show hobbies list..
        /// </summary>
        public static string Register_Text3 {
            get {
                return ResourceManager.GetString("Register_Text3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change value is required..
        /// </summary>
        public static string Change_Required_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("Change_Required_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discount value must be a positive number..
        /// </summary>
        public static string Discount_DataType_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("Discount_DataType_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discount value is required..
        /// </summary>
        public static string Discount_Required_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("Discount_Required_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EndTime value is required..
        /// </summary>
        public static string EndTime_Required_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("EndTime_Required_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price value must be a positive number..
        /// </summary>
        public static string Price_DataType_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("Price_DataType_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price value is required..
        /// </summary>
        public static string Price_Required_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("Price_Required_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start value must be DateTime..
        /// </summary>
        public static string Start_DataType_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("Start_DataType_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to value Start is required..
        /// </summary>
        public static string Start_Required_ErrorMessage
        {
            get
            {
                return ResourceManager.GetString("Start_Required_ErrorMessage", resourceCulture);
            }
        }
    }
}
