//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATBillReport
    {
        public int BillingID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<double> PreviousBill { get; set; }
        public Nullable<double> CurrentCharges { get; set; }
        public string AccNO { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<double> WireLessCharge { get; set; }
        public Nullable<double> TVCharge { get; set; }
        public Nullable<double> VoiceCharge { get; set; }
        public string Area { get; set; }
        public string AreaCode { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
    }
}
