//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C1NWindEntities : DbContext
    {
        public C1NWindEntities()
            : base("name=C1NWindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<ATBillReport> ATBillReports { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Customers_Map> Customers_Map { get; set; }
        public virtual DbSet<DoughtNutChartData> DoughtNutChartDatas { get; set; }
        public virtual DbSet<EmployeeTerritory> EmployeeTerritories { get; set; }
        public virtual DbSet<EmployeeTravelExp> EmployeeTravelExps { get; set; }
        public virtual DbSet<GanttChartData> GanttChartDatas { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<MarketingProjectPlanData> MarketingProjectPlanDatas { get; set; }
        public virtual DbSet<MonthlyBudget> MonthlyBudgets { get; set; }
        public virtual DbSet<MonthlyProjectCostTracking> MonthlyProjectCostTrackings { get; set; }
        public virtual DbSet<Order_Detail> Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PolarSample> PolarSamples { get; set; }
        public virtual DbSet<PriceComparison> PriceComparisons { get; set; }
        public virtual DbSet<SalesByQuarter> SalesByQuarters { get; set; }
        public virtual DbSet<ScatterPoint> ScatterPoints { get; set; }
        public virtual DbSet<StateNamesGeo> StateNamesGeos { get; set; }
        public virtual DbSet<StockChartData> StockChartDatas { get; set; }
        public virtual DbSet<SystemAdaptability> SystemAdaptabilities { get; set; }
    }
}
