//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoughtNutChartData
    {
        public int ID { get; set; }
        public string Task { get; set; }
        public Nullable<int> Worker1 { get; set; }
        public Nullable<int> Worker2 { get; set; }
    }
}
