//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingProjectPlanData
    {
        public int Task_ID { get; set; }
        public string Task_Name { get; set; }
        public string Task_Status { get; set; }
        public string Task_Owner { get; set; }
        public string AssignTO { get; set; }
        public Nullable<System.DateTime> Anticipated_StartDate { get; set; }
        public Nullable<System.DateTime> Anticipated_EndDate { get; set; }
        public Nullable<System.DateTime> Actual_StartDate { get; set; }
        public Nullable<System.DateTime> Actual_EndDate { get; set; }
        public Nullable<int> Estimated_Cost { get; set; }
        public Nullable<int> Actual_Cost { get; set; }
    }
}
