//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceComparison
    {
        public int Product_ID { get; set; }
        public string Product_Type { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Price_2013 { get; set; }
        public Nullable<int> Price_2014 { get; set; }
        public byte[] Product_Type_Photo { get; set; }
    }
}
