//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColumnGroups.Localization {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColumnGroups.Localization.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ~/Content/css/gcicons.css.
        /// </summary>
        public static string GcIconsCssPath {
            get {
                return ResourceManager.GetString("GcIconsCssPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This example shows a table with financial data. The data contains two column groups, one showing fund performance and one showing fund composition..
        /// </summary>
        public static string Index_View_Financial_P1 {
            get {
                return ResourceManager.GetString("Index_View_Financial_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The grids below have hierarchical column structures where some columns contain groups of columns..
        /// </summary>
        public static string Index_View_P1 {
            get {
                return ResourceManager.GetString("Index_View_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The columns have multi-level, merged headers that reflect the structure of the data. Clicking header cells selects the whole group..
        /// </summary>
        public static string Index_View_P2 {
            get {
                return ResourceManager.GetString("Index_View_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Both examples create the headers using the &lt;b&gt;ColumnGroupProvider&lt;/b&gt; class which is defined in the &lt;b&gt;wijmo.grid.columngroups&lt;/b&gt; extension module..
        /// </summary>
        public static string Index_View_P3 {
            get {
                return ResourceManager.GetString("Index_View_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This example is based on the &lt;a href=&quot;http://www.w3.org/TR/html401/struct/tables.html&quot;&gt;W3 page that describes the table element&lt;/a&gt;. It shows a simple table with a column group that shows &quot;Average&quot; weight and height values:.
        /// </summary>
        public static string Index_View_W3C_P1 {
            get {
                return ResourceManager.GetString("Index_View_W3C_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ComponentOne.
        /// </summary>
        public static string Layout_ComponentOne {
            get {
                return ResourceManager.GetString("Layout_ComponentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to http://developer.mescius.com/.
        /// </summary>
        public static string Layout_Url {
            get {
                return ResourceManager.GetString("Layout_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MESCIUS inc. All rights reserved.
        /// </summary>
        public static string Layout_License1 {
            get {
                return ResourceManager.GetString("Layout_License1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All product and company names here in may be trademarks of their respective owners..
        /// </summary>
        public static string Layout_License2 {
            get {
                return ResourceManager.GetString("Layout_License2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ASP.NET MVC FlexGrid Column Groups.
        /// </summary>
        public static string Layout_LongTitle {
            get {
                return ResourceManager.GetString("Layout_LongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/aspnet-mvc.
        /// </summary>
        public static string Layout_ProductUrl {
            get {
                return ResourceManager.GetString("Layout_ProductUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MVC FlexGrid Column Groups.
        /// </summary>
        public static string Layout_ShortTitle {
            get {
                return ResourceManager.GetString("Layout_ShortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to - C1 ASP.NET MVC.
        /// </summary>
        public static string Layout_TitleSuffix {
            get {
                return ResourceManager.GetString("Layout_TitleSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Have you seen this? C1Studio MVC Edition Controls.
        /// </summary>
        public static string Layout_TwitterText {
            get {
                return ResourceManager.GetString("Layout_TwitterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Financial table example.
        /// </summary>
        public static string SectionTitle_Financial {
            get {
                return ResourceManager.GetString("SectionTitle_Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to W3C table example.
        /// </summary>
        public static string SectionTitle_W3C {
            get {
                return ResourceManager.GetString("SectionTitle_W3C", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to About.
        /// </summary>
        public static string SiteNav_About {
            get {
                return ResourceManager.GetString("SiteNav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/aspnet-mvc.
        /// </summary>
        public static string SiteNav_AboutUrl {
            get {
                return ResourceManager.GetString("SiteNav_AboutUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Download.
        /// </summary>
        public static string SiteNav_FreeTrial {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/download/componentone-studio.
        /// </summary>
        public static string SiteNav_FreeTrialUrl {
            get {
                return ResourceManager.GetString("SiteNav_FreeTrialUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Home.
        /// </summary>
        public static string SiteNav_Home {
            get {
                return ResourceManager.GetString("SiteNav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Pricing.
        /// </summary>
        public static string SiteNav_Pricing {
            get {
                return ResourceManager.GetString("SiteNav_Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/pricing.
        /// </summary>
        public static string SiteNav_PricingUrl {
            get {
                return ResourceManager.GetString("SiteNav_PricingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Support.
        /// </summary>
        public static string SiteNav_Support {
            get {
                return ResourceManager.GetString("SiteNav_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/my-account/my-support.
        /// </summary>
        public static string SiteNav_SupportUrl {
            get {
                return ResourceManager.GetString("SiteNav_SupportUrl", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Demos.
        /// </summary>
        public static string SiteNav_Demos {
            get {
                return ResourceManager.GetString("SiteNav_Demos", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/componentone/demos.
        /// </summary>
        public static string SiteNav_DemosUrl {
            get {
                return ResourceManager.GetString("SiteNav_DemosUrl", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Docs.
        /// </summary>
        public static string SiteNav_Docs {
            get {
                return ResourceManager.GetString("SiteNav_Docs", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/componentone/docs/mvc/online-mvc-core/overview.html.
        /// </summary>
        public static string SiteNav_DocsUrl {
            get {
                return ResourceManager.GetString("SiteNav_DocsUrl", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to Samples.
        /// </summary>
        public static string SiteNav_Samples {
            get {
                return ResourceManager.GetString("SiteNav_Samples", resourceCulture);
            }
        }

        /// <summary>
        ///    Looks up a localized string similar to https://developer.mescius.com/componentone/samples.
        /// </summary>
        public static string SiteNav_SamplesUrl {
            get {
                return ResourceManager.GetString("SiteNav_SamplesUrl", resourceCulture);
            }
        }        
    }
}
