//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Accordion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Accordion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Accordion", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The AccordionPane.IsCollapsed property allows you to set a pane as collapsed or not..
        /// </summary>
        internal static string AccordionPane_Text0 {
            get {
                return ResourceManager.GetString("AccordionPane_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This sample demonstrates the usage of IsCollapsed property of Pane for the Accordion control..
        /// </summary>
        internal static string AccordionPane_Text1 {
            get {
                return ResourceManager.GetString("AccordionPane_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The first Pane is configured to have the IsCollapsed property as true meanwhile the second is set to false so it is an expanded pane..
        /// </summary>
        internal static string AccordionPane_Text2 {
            get {
                return ResourceManager.GetString("AccordionPane_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can collapse pane.
        /// </summary>
        internal static string AccordionPane_Text3 {
            get {
                return ResourceManager.GetString("AccordionPane_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Change the properties of this Accordion..
        /// </summary>
        internal static string Index_Pane_Text0 {
            get {
                return ResourceManager.GetString("Index_Pane_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon in the pane headers.
        /// </summary>
        internal static string Index_Pane_Text1 {
            get {
                return ResourceManager.GetString("Index_Pane_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand panes when selecting with the keyboard.
        /// </summary>
        internal static string Index_Pane_Text2 {
            get {
                return ResourceManager.GetString("Index_Pane_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animate pane collapse/expand.
        /// </summary>
        internal static string Index_Pane_Text3 {
            get {
                return ResourceManager.GetString("Index_Pane_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can collapse all panes.
        /// </summary>
        internal static string Index_Pane_Text4 {
            get {
                return ResourceManager.GetString("Index_Pane_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can expand multiple panes.
        /// </summary>
        internal static string Index_Pane_Text5 {
            get {
                return ResourceManager.GetString("Index_Pane_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Accordion control allows you to organize content into collapsible panes..
        /// </summary>
        internal static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample demonstrates the usage and main properties of the Accordion control..
        /// </summary>
        internal static string Index_Text1 {
            get {
                return ResourceManager.GetString("Index_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first pane show some feature settings of the Accordion control which you can try changing them to know how the Accordion works. &lt;br /&gt;
        ///The remaing panes just show example contents for the Accordion demonstration..
        /// </summary>
        internal static string Index_Text2 {
            get {
                return ResourceManager.GetString("Index_Text2", resourceCulture);
            }
        }
    }
}
