//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Barcode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Barcode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Barcode", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This view shows basic features of Barcode for ASP.NET MVC..
        /// </summary>
        internal static string Barcode_Description_Text0 {
            get {
                return ResourceManager.GetString("Barcode_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode control.
        /// </summary>
        internal static string Barcode_Index_Text0 {
            get {
                return ResourceManager.GetString("Barcode_Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Barcode_Index_Text1 {
            get {
                return ResourceManager.GetString("Barcode_Index_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string Barcode_Index_Text2 {
            get {
                return ResourceManager.GetString("Barcode_Index_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Barcode_Index_Text3 {
            get {
                return ResourceManager.GetString("Barcode_Index_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Codabar&lt;/b&gt; control is used to display &lt;b&gt;Codabar&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Codabar_Description_Text0 {
            get {
                return ResourceManager.GetString("Codabar_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Code128&lt;/b&gt; control is used to display &lt;b&gt;Code128&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Code128_Description_Text0 {
            get {
                return ResourceManager.GetString("Code128_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Code39&lt;/b&gt; control is used to display &lt;b&gt;Code39&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Code39_Description_Text0 {
            get {
                return ResourceManager.GetString("Code39_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Code49&lt;/b&gt; control is used to display &lt;b&gt;Code49&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Code49_Description_Text0 {
            get {
                return ResourceManager.GetString("Code49_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Code93&lt;/b&gt; control is used to display &lt;b&gt;Code93&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Code93_Description_Text0 {
            get {
                return ResourceManager.GetString("Code93_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;DataMatrix&lt;/b&gt; control is used to display &lt;b&gt;DataMatrix&lt;/b&gt; barcodes with specification versions in the range from &lt;b&gt;ECC 000&lt;/b&gt; to &lt;b&gt;ECC 140&lt;/b&gt;..
        /// </summary>
        internal static string DataMatrixEcc000_Description_Text0 {
            get {
                return ResourceManager.GetString("DataMatrixEcc000_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;DataMatrixEcc200&lt;/b&gt; control is used to display &lt;b&gt;DataMatrix ECC-200&lt;/b&gt; barcodes..
        /// </summary>
        internal static string DataMatrixEcc200_Description_Text0 {
            get {
                return ResourceManager.GetString("DataMatrixEcc200_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Ean13&lt;/b&gt; control is used to display &lt;b&gt;EAN-13&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Ean13_Description_Text0 {
            get {
                return ResourceManager.GetString("Ean13_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Ean8&lt;/b&gt; control is used to display &lt;b&gt;EAN-8&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Ean8_Description_Text0 {
            get {
                return ResourceManager.GetString("Ean8_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1DataBarExpandedStacked&lt;/b&gt; control is used to display &lt;b&gt;GS1 DataBar Expanded Stacked&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1DataBarExpandedStacked_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1DataBarExpandedStacked_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1DataBarExpanded&lt;/b&gt; control is used to display &lt;b&gt;GS1 DataBar Expanded&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1DataBarExpanded_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1DataBarExpanded_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1DataBarLimited&lt;/b&gt; control is used to display &lt;b&gt;GS1 DataBar Limited&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1DataBarLimited_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1DataBarLimited_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1DataBarOmnidirectional&lt;/b&gt; control is used to display &lt;b&gt;GS1 DataBar Omnidirectional&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1DataBarOmnidirectional_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1DataBarOmnidirectional_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1DataBarStackedOmnidirectional&lt;/b&gt; control is used to display &lt;b&gt;GS1 DataBar StackedOmnidirectional&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1DataBarStackedOmnidirectional_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1DataBarStackedOmnidirectional_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1DataBarStacked&lt;/b&gt; control is used to display &lt;b&gt;GS1 DataBar Stacked&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1DataBarStacked_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1DataBarStacked_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1DataBarTruncated&lt;/b&gt; control is used to display &lt;b&gt;GS1 DataBar Truncated&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1DataBarTruncated_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1DataBarTruncated_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Gs1_128&lt;/b&gt; control is used to display &lt;b&gt;GS1-128&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Gs1_128_Description_Text0 {
            get {
                return ResourceManager.GetString("Gs1_128_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Interleaved2of5&lt;/b&gt; control is used to display &lt;b&gt;Interleaved 2 of 5&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Interleaved2of5_Description_Text0 {
            get {
                return ResourceManager.GetString("Interleaved2of5_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Itf14&lt;/b&gt; control is used to display &lt;b&gt;ITF-14&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Itf14_Description_Text0 {
            get {
                return ResourceManager.GetString("Itf14_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;JapanesePostal&lt;/b&gt; control is used to display &lt;b&gt;Japanese Postal&lt;/b&gt; barcodes..
        /// </summary>
        internal static string JapanesePostal_Description_Text0 {
            get {
                return ResourceManager.GetString("JapanesePostal_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;MicroPdf417&lt;/b&gt; control is used to display &lt;b&gt;MicroPDF417&lt;/b&gt; barcodes..
        /// </summary>
        internal static string MicroPdf417_Description_Text0 {
            get {
                return ResourceManager.GetString("MicroPdf417_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;Pdf417&lt;/b&gt; control is used to display &lt;b&gt;PDF417&lt;/b&gt; barcodes..
        /// </summary>
        internal static string Pdf417_Description_Text0 {
            get {
                return ResourceManager.GetString("Pdf417_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;QrCode&lt;/b&gt; control is used to display &lt;b&gt;QR code&lt;/b&gt; barcodes..
        /// </summary>
        internal static string QRCode_Description_Text0 {
            get {
                return ResourceManager.GetString("QRCode_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;UpcA&lt;/b&gt; control is used to display &lt;b&gt;UPC-A&lt;/b&gt; barcodes..
        /// </summary>
        internal static string UpcA_Description_Text0 {
            get {
                return ResourceManager.GetString("UpcA_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;UpcE0&lt;/b&gt; control is used to display &lt;b&gt;UPC-E0&lt;/b&gt; barcodes..
        /// </summary>
        internal static string UpcE0_Description_Text0 {
            get {
                return ResourceManager.GetString("UpcE0_Description_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;UpcE1&lt;/b&gt; control is used to display &lt;b&gt;UPC-E1&lt;/b&gt; barcodes..
        /// </summary>
        internal static string UpcE1_Description_Text0 {
            get {
                return ResourceManager.GetString("UpcE1_Description_Text0", resourceCulture);
            }
        }
    }
}
