//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinearGauge {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinearGauge() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LinearGauge", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to use the Direction property with the LinearGauge control..
        /// </summary>
        internal static string Direction_Text0 {
            get {
                return ResourceManager.GetString("Direction_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to use the IsReadOnly and Step properties with the LinearGauge control..
        /// </summary>
        internal static string Editing_Text0 {
            get {
                return ResourceManager.GetString("Editing_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;ShowTicks:&lt;/b&gt; determines whether the gauge should display tickmarks at each step or tickSpacing value..
        /// </summary>
        internal static string Editing_Text1 {
            get {
                return ResourceManager.GetString("Editing_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;ShowTickText:&lt;/b&gt; determines whether the gauge should display the text value of each tick mark..
        /// </summary>
        internal static string Editing_Text2 {
            get {
                return ResourceManager.GetString("Editing_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;HandleWheel:&lt;/b&gt; determines whether the user can edit the gauge value using the mouse wheel..
        /// </summary>
        internal static string Editing_Text3 {
            get {
                return ResourceManager.GetString("Editing_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows the basic usage of the LinearGauge control..
        /// </summary>
        internal static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The example demonstrates how to use Ranges with LinearGauge..
        /// </summary>
        internal static string Ranges_Text0 {
            get {
                return ResourceManager.GetString("Ranges_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom CSS.
        /// </summary>
        internal static string Scaling_CustomCSS {
            get {
                return ResourceManager.GetString("Scaling_CustomCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Styles.
        /// </summary>
        internal static string Scaling_DefaultStyles {
            get {
                return ResourceManager.GetString("Scaling_DefaultStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the gauges to change the color:.
        /// </summary>
        internal static string Scaling_Text0 {
            get {
                return ResourceManager.GetString("Scaling_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value bound to the gauges:.
        /// </summary>
        internal static string Scaling_Text1 {
            get {
                return ResourceManager.GetString("Scaling_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to scale the LinearGauge control..
        /// </summary>
        internal static string Scaling_Text2 {
            get {
                return ResourceManager.GetString("Scaling_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This example demonstrates how to use the ShowText property with the LinearGauge control..
        /// </summary>
        internal static string ShowText_Text {
            get {
                return ResourceManager.GetString("ShowText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this example, we have added the &quot;custom-gauge&quot; CSS class to LinearGauge, and define CSS rules to create an orange pointer..
        /// </summary>
        internal static string Styling_Text0 {
            get {
                return ResourceManager.GetString("Styling_Text0", resourceCulture);
            }
        }
    }
}
