//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Popup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Popup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Popup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show Popup form.
        /// </summary>
        internal static string Content_ClickToShowPopupForm {
            get {
                return ResourceManager.GetString("Content_ClickToShowPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Content_Close {
            get {
                return ResourceManager.GetString("Content_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Popup&lt;br&gt;
        ///This is a multi-line message!.
        /// </summary>
        internal static string Content_Content1 {
            get {
                return ResourceManager.GetString("Content_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The content wrapped in a regular HTML tag).
        /// </summary>
        internal static string Content_Description1 {
            get {
                return ResourceManager.GetString("Content_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (The content wrapped in a text tag).
        /// </summary>
        internal static string Content_Description2 {
            get {
                return ResourceManager.GetString("Content_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Contents.
        /// </summary>
        internal static string Content_PopupContents {
            get {
                return ResourceManager.GetString("Content_PopupContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string Content_SaveChanges {
            get {
                return ResourceManager.GetString("Content_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Popup&lt;br&gt;This is a popup with input controls!.
        /// </summary>
        internal static string Content_Text0 {
            get {
                return ResourceManager.GetString("Content_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of Popup can be set with elements wrapped in a regular HTML tag or text tag (Razor syntax)..
        /// </summary>
        internal static string Content_Text1 {
            get {
                return ResourceManager.GetString("Content_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Content_Title {
            get {
                return ResourceManager.GetString("Content_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show Popup form.
        /// </summary>
        internal static string Index_ClickToShowPopupForm {
            get {
                return ResourceManager.GetString("Index_ClickToShowPopupForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show Popup with Events.
        /// </summary>
        internal static string Index_ClickToShowPopupWithEvents {
            get {
                return ResourceManager.GetString("Index_ClickToShowPopupWithEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Index_Close {
            get {
                return ResourceManager.GetString("Index_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Popup&lt;br&gt;
        ///        This is a multi-line message!.
        /// </summary>
        internal static string Index_Content1 {
            get {
                return ResourceManager.GetString("Index_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Popup&lt;br&gt;
        ///        This is a multi-line message!.
        /// </summary>
        internal static string Index_Content2 {
            get {
                return ResourceManager.GetString("Index_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowTrigger and HideTrigger properties will follow the Settings below.
        /// </summary>
        internal static string Index_Description4 {
            get {
                return ResourceManager.GetString("Index_Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the Trigger properties, to change whenever the Popup will show or hidden..
        /// </summary>
        internal static string Index_Description5 {
            get {
                return ResourceManager.GetString("Index_Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string Index_EnterEmail {
            get {
                return ResourceManager.GetString("Index_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;IsDraggable&lt;/b&gt;: Gets or sets a value that determines whether the popup can be dragged with the mouse by its header. The header is identified by the &apos;.wj-dialog-header&apos; or &apos;.modal-header&apos; CSS selectors. If the dialog does not contain any elements with the &apos;wj-dialog-header&apos;or &apos;modal-header&apos; classes, users will not be able to drag the popup..
        /// </summary>
        internal static string Index_IsDraggable_Description {
            get {
                return ResourceManager.GetString("Index_IsDraggable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientDragged&lt;/b&gt;: Gets or sets the client function which occurs after the Popup has been dragged..
        /// </summary>
        internal static string Index_OnClientDragged_Description {
            get {
                return ResourceManager.GetString("Index_OnClientDragged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientDragging&lt;/b&gt;: Gets or sets the client function which occurs when the Popup is about to be dragged..
        /// </summary>
        internal static string Index_OnClientDragging_Description {
            get {
                return ResourceManager.GetString("Index_OnClientDragging_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientPositionChanged&lt;/b&gt;: Gets or sets the client function which occurs while the user moves the Popup, between the Dragging and Dragged events, after the PositionChanging event..
        /// </summary>
        internal static string Index_OnClientPositionChanged_Description {
            get {
                return ResourceManager.GetString("Index_OnClientPositionChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientPositionChanging&lt;/b&gt;: Gets or sets the client function which occurs while the user moves the Popup, between the Dragging and Dragged events..
        /// </summary>
        internal static string Index_OnClientPositionChanging_Description {
            get {
                return ResourceManager.GetString("Index_OnClientPositionChanging_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientResized&lt;/b&gt;: Gets or sets the client function which occurs after the Popup has been resized..
        /// </summary>
        internal static string Index_OnClientResized_Description {
            get {
                return ResourceManager.GetString("Index_OnClientResized_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientResizing&lt;/b&gt;: Gets or sets the client function which occurs when the Popup is about to be resized..
        /// </summary>
        internal static string Index_OnClientResizing_Description {
            get {
                return ResourceManager.GetString("Index_OnClientResizing_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientSizeChanged&lt;/b&gt;: Gets or sets the client function which occurs while the user resizes the Popup, between the resizing and resized events, after the SizeChanging event..
        /// </summary>
        internal static string Index_OnClientSizeChanged_Description {
            get {
                return ResourceManager.GetString("Index_OnClientSizeChanged_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;OnClientSizeChanging&lt;/b&gt;: Gets or sets the client function which occurs while the user resizes the Popup, between the resizing and resized events..
        /// </summary>
        internal static string Index_OnClientSizeChanging_Description {
            get {
                return ResourceManager.GetString("Index_OnClientSizeChanging_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string Index_SaveChanges {
            get {
                return ResourceManager.GetString("Index_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Popup&lt;br&gt;This is a multiline message!.
        /// </summary>
        internal static string Index_Text0 {
            get {
                return ResourceManager.GetString("Index_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popovers (Popups with owner elements).
        /// </summary>
        internal static string Index_Text1 {
            get {
                return ResourceManager.GetString("Index_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popups may have owner elements that can be used to control their visibility. The ShowTrigger and HideTrigger properties determine whether the Popups should be shown or hidden when the owner element is clicked or when the popup loses focus..
        /// </summary>
        internal static string Index_Text2 {
            get {
                return ResourceManager.GetString("Index_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;IsResizable&lt;/b&gt;: Gets or sets a value that determines whether the popup can be resized by dragging its edges with the mouse..
        /// </summary>
        internal static string Index_Text3 {
            get {
                return ResourceManager.GetString("Index_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Index_Title1 {
            get {
                return ResourceManager.GetString("Index_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Index_Title2 {
            get {
                return ResourceManager.GetString("Index_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Index_Title3 {
            get {
                return ResourceManager.GetString("Index_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize Trigger.
        /// </summary>
        internal static string Index_Title4 {
            get {
                return ResourceManager.GetString("Index_Title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password:.
        /// </summary>
        internal static string PopupDialog_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("PopupDialog_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        internal static string PopupDialog_ConfirmPassword {
            get {
                return ResourceManager.GetString("PopupDialog_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string PopupDialog_CreateAccount {
            get {
                return ResourceManager.GetString("PopupDialog_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password:.
        /// </summary>
        internal static string PopupDialog_CurrentPassword {
            get {
                return ResourceManager.GetString("PopupDialog_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Submit Result.
        /// </summary>
        internal static string PopupDialog_Custom {
            get {
                return ResourceManager.GetString("PopupDialog_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input any text:.
        /// </summary>
        internal static string PopupDialog_CustomInput {
            get {
                return ResourceManager.GetString("PopupDialog_CustomInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        internal static string PopupDialog_DonTHaveAnAccountYet {
            get {
                return ResourceManager.GetString("PopupDialog_DonTHaveAnAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string PopupDialog_EditAccount {
            get {
                return ResourceManager.GetString("PopupDialog_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string PopupDialog_Email {
            get {
                return ResourceManager.GetString("PopupDialog_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 2 characters or more..
        /// </summary>
        internal static string PopupDialog_InputTitle2 {
            get {
                return ResourceManager.GetString("PopupDialog_InputTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 4 characters or more..
        /// </summary>
        internal static string PopupDialog_InputTitle4 {
            get {
                return ResourceManager.GetString("PopupDialog_InputTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging in via Facebook....
        /// </summary>
        internal static string PopupDialog_LoggingInViaFacebook {
            get {
                return ResourceManager.GetString("PopupDialog_LoggingInViaFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging in via Google....
        /// </summary>
        internal static string PopupDialog_LoggingInViaGoogle {
            get {
                return ResourceManager.GetString("PopupDialog_LoggingInViaGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string PopupDialog_LogIn {
            get {
                return ResourceManager.GetString("PopupDialog_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your Facebook account.
        /// </summary>
        internal static string PopupDialog_LogInUsingYourFacebookAccount {
            get {
                return ResourceManager.GetString("PopupDialog_LogInUsingYourFacebookAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your Google account.
        /// </summary>
        internal static string PopupDialog_LogInUsingYourGoogleAccount {
            get {
                return ResourceManager.GetString("PopupDialog_LogInUsingYourGoogleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modal.
        /// </summary>
        internal static string PopupDialog_Modal {
            get {
                return ResourceManager.GetString("PopupDialog_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string PopupDialog_Name {
            get {
                return ResourceManager.GetString("PopupDialog_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name:.
        /// </summary>
        internal static string PopupDialog_NewName {
            get {
                return ResourceManager.GetString("PopupDialog_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password:.
        /// </summary>
        internal static string PopupDialog_NewPassword {
            get {
                return ResourceManager.GetString("PopupDialog_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PopupDialog_Password {
            get {
                return ResourceManager.GetString("PopupDialog_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string PopupDialog_RememberMe {
            get {
                return ResourceManager.GetString("PopupDialog_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form is submitted with custom submit result and inputted text is.
        /// </summary>
        internal static string PopupDialog_ResultSubmit {
            get {
                return ResourceManager.GetString("PopupDialog_ResultSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs (Popups with no owner).
        /// </summary>
        internal static string PopupDialog_Text0 {
            get {
                return ResourceManager.GetString("PopupDialog_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs are Popups with no owner element. They must be shown by calling the show method.&lt;br /&gt;
        ///    Dialogs can be modal or modeless. Modal dialogs have a dark backdrop, and if their HideTrigger property is set to None, they cannot lose focus and must be dismissed by the user, either by pressing escape or by clicking an element on the dialog itself..
        /// </summary>
        internal static string PopupDialog_Text1 {
            get {
                return ResourceManager.GetString("PopupDialog_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string PopupDialog_Title1 {
            get {
                return ResourceManager.GetString("PopupDialog_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string PopupDialog_Title2 {
            get {
                return ResourceManager.GetString("PopupDialog_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account.
        /// </summary>
        internal static string PopupDialog_Title3 {
            get {
                return ResourceManager.GetString("PopupDialog_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Submit Result.
        /// </summary>
        internal static string PopupDialog_Title5 {
            get {
                return ResourceManager.GetString("PopupDialog_Title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account.
        /// </summary>
        internal static string PopupDialog_UpdateAccount {
            get {
                return ResourceManager.GetString("PopupDialog_UpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Popup position to set where the popup should be displayed with respect to the owner element..
        /// </summary>
        internal static string PopupPosition_Description {
            get {
                return ResourceManager.GetString("PopupPosition_Description", resourceCulture);
            }
        }
    }
}
