//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Validation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Validation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change value is required..
        /// </summary>
        internal static string Change_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("Change_Required_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discount value must be a positive number..
        /// </summary>
        internal static string Discount_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("Discount_DataType_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discount value is required..
        /// </summary>
        internal static string Discount_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("Discount_Required_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EndTime value is required..
        /// </summary>
        internal static string EndTime_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("EndTime_Required_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price value must be a positive number..
        /// </summary>
        internal static string Price_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("Price_DataType_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Price value is required..
        /// </summary>
        internal static string Price_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("Price_Required_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations to .
        /// </summary>
        internal static string Register_CongratulationsTo {
            get {
                return ResourceManager.GetString("Register_CongratulationsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string Register_CreateAnAccount {
            get {
                return ResourceManager.GetString("Register_CreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is not a valid e-mail address..
        /// </summary>
        internal static string Register_Email_ErrorMessage {
            get {
                return ResourceManager.GetString("Register_Email_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press SPACE key to show hobbies list..
        /// </summary>
        internal static string Register_HobbiesPrompt {
            get {
                return ResourceManager.GetString("Register_HobbiesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must be alphanumeric and contains 4 to 10 characters..
        /// </summary>
        internal static string Register_Name_ErrorMessage {
            get {
                return ResourceManager.GetString("Register_Name_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register_Register {
            get {
                return ResourceManager.GetString("Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Complete.
        /// </summary>
        internal static string Register_RegistrationComplete {
            get {
                return ResourceManager.GetString("Register_RegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Your registration has been successfuly submitted..
        /// </summary>
        internal static string Register_RegistrationSuccessfully {
            get {
                return ResourceManager.GetString("Register_RegistrationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sample shows the basic usage of the unobtrusive validation..
        /// </summary>
        internal static string Register_Text0 {
            get {
                return ResourceManager.GetString("Register_Text0", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Birthdate field is required..
        /// </summary>
        internal static string Required_Birthdate_ErrorMessage {
            get {
                return ResourceManager.GetString("Required_Birthdate_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Country field is required..
        /// </summary>
        internal static string Required_Country_ErrorMessage {
            get {
                return ResourceManager.GetString("Required_Country_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Email field is required..
        /// </summary>
        internal static string Required_Email_ErrorMessage {
            get {
                return ResourceManager.GetString("Required_Email_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Industry field is required..
        /// </summary>
        internal static string Required_Industry_ErrorMessage {
            get {
                return ResourceManager.GetString("Required_Industry_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Name field is required..
        /// </summary>
        internal static string Required_Name_ErrorMessage {
            get {
                return ResourceManager.GetString("Required_Name_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Phone field is required..
        /// </summary>
        internal static string Required_Phone_ErrorMessage {
            get {
                return ResourceManager.GetString("Required_Phone_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start value must be DateTime..
        /// </summary>
        internal static string Start_DataType_ErrorMessage {
            get {
                return ResourceManager.GetString("Start_DataType_ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start value is required..
        /// </summary>
        internal static string Start_Required_ErrorMessage {
            get {
                return ResourceManager.GetString("Start_Required_ErrorMessage", resourceCulture);
            }
        }
    }
}
