//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Richard Arms, Arms CandleVolume charts are a combination of EquiVolume and CandleVolume charts..
        /// </summary>
        internal static string ArmsCandleVolume_Text0 {
            get {
                return ResourceManager.GetString("ArmsCandleVolume_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Richard Arms, Arms CandleVolume charts are a combination of EquiVolume and CandleVolume charts..
        /// </summary>
        internal static string ArmsCandleVolume_Text1 {
            get {
                return ResourceManager.GetString("ArmsCandleVolume_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandleVolume charts are identical to standard Candlestick charts, except that the width of each bar is determined by a fifth value, volume..
        /// </summary>
        internal static string CandleVolume_Text0 {
            get {
                return ResourceManager.GetString("CandleVolume_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandleVolume charts are identical to standard Candlestick charts, except that the width of each bar is determined by a fifth value, volume..
        /// </summary>
        internal static string CandleVolume_Text1 {
            get {
                return ResourceManager.GetString("CandleVolume_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnVolume charts are similar to Column charts, except that they accept a second value, volume, which dictates the width of each bar..
        /// </summary>
        internal static string ColumnVolume_Text0 {
            get {
                return ResourceManager.GetString("ColumnVolume_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnVolume charts are similar to Column charts, except that they accept a second value, volume, which dictates the width of each bar..
        /// </summary>
        internal static string ColumnVolume_Text1 {
            get {
                return ResourceManager.GetString("ColumnVolume_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquiVolume charts are similar to Candlestick charts, but they only show the high and low values..
        /// </summary>
        internal static string EquiVolume_Text0 {
            get {
                return ResourceManager.GetString("EquiVolume_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In addition, the width of each bar is determined by a fifth value, volume..
        /// </summary>
        internal static string EquiVolume_Text1 {
            get {
                return ResourceManager.GetString("EquiVolume_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquiVolume charts are similar to Candlestick charts, but they only show the high and low values..
        /// </summary>
        internal static string EquiVolume_Text2 {
            get {
                return ResourceManager.GetString("EquiVolume_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event annotations are used to mark important events that can be attached to a specific data point on the FinancialChart. Hovering over the event annotation will reveal the full details of the event..
        /// </summary>
        internal static string EventAnnotations_Text0 {
            get {
                return ResourceManager.GetString("EventAnnotations_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event annotations are used to mark important events that can be attached to a specific data point on the FinancialChart. Hovering over the event annotation will reveal the full details of the event..
        /// </summary>
        internal static string EventAnnotations_Text1 {
            get {
                return ResourceManager.GetString("EventAnnotations_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Why the hot IPO market is cooling off?&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip1 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;BD Board Declares Dividend&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip10 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;The Board of Directors of BD (Becton, Dickinson and Company) (NYSE: BDX) has declared a quarterly dividend of 60.0 cents per common share payable on June ....
        /// </summary>
        internal static string EventAnnotations_Tooltip11 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Box Sets Date to Announce First Quarter Fiscal 2016 Financial Results&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip12 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Box today announced that it will report financial results for its first quarter which ended April 30, 2015, following the close of the market on Wednesday, June 10, 2015..
        /// </summary>
        internal static string EventAnnotations_Tooltip13 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Making Money With Charles Payne: 05/21/15&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip14 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Best Buy to move sideways: Analyst&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip15 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Macquarie Upgrades Hercules Technology, Likes Dividend&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip16 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;In a report published Tuesday, Macquarie analysts upgraded their rating on Hercules Technology Growth Capital, Inc. (NYSE: HTGX), with a price target of $14. The analysts believe that the company&apos;s dividend ....
        /// </summary>
        internal static string EventAnnotations_Tooltip17 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;The U.S. Department of Justice Selects Box to Enable Enterprise File Sharing&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip18 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Box today announced that it is working with the U.S. Department of Justice to deliver file sharing and information management to the agency’s workforce. After rigorous assessment, Box will receive an agency Authorization to Operate this week, allowing the DOJ to leverage the platform across all its component agencies..
        /// </summary>
        internal static string EventAnnotations_Tooltip19 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Tech IPO market healthy?&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip2 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Box Enables Improved Collaboration and Content Sharing at the ASPCA&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip20 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Box today announced that the ASPCA® , the first humane society established in North America, is bringing Box’s cloud content sharing and collaboration platform to its employees..
        /// </summary>
        internal static string EventAnnotations_Tooltip21 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Center for Sustainable Energy Leverages Box to Power California Clean Vehicle Rebate Project&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip3 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Box today announced that the Center for Sustainable Energy, a nonprofit organization committed to accelerating the transition to a sustainable world powered by clean energy, is leveraging the Box platform to power a cloud-based document submission and review process as part of the Clean Vehicle Rebate Project..
        /// </summary>
        internal static string EventAnnotations_Tooltip4 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Box to Present at the J.P. Morgan Technology, Media and Telecom Conference&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip5 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Box today announced that Aaron Levie, co-founder and CEO, will participate in the J.P. Morgan Technology, Media and Telecom Conference in Boston on Monday, May 18, 2015..
        /// </summary>
        internal static string EventAnnotations_Tooltip6 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;BD Receives FDA Clearance for a Novel Infusion Set with BD FlowSmart™ Technology to Enhance the Use of Insulin Pumps&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip7 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Unique Side-Ported Catheter Designed to Offer Consistent Insulin Delivery and Fewer Flow Interruptions including Silent Occlusions Infusion Set Developed in Collaboration with JDRF and Helmsley Charitable ....
        /// </summary>
        internal static string EventAnnotations_Tooltip8 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Wall Street tech debutant Box dismisses doubters&lt;/b&gt;.
        /// </summary>
        internal static string EventAnnotations_Tooltip9 {
            get {
                return ResourceManager.GetString("EventAnnotations_Tooltip9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci tool is used for trend analysis in financial charts. With the help of range selector, you can choose data range for calculation..
        /// </summary>
        internal static string FibonacciTool_Text0 {
            get {
                return ResourceManager.GetString("FibonacciTool_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci tool is used for trend analysis in financial charts..
        /// </summary>
        internal static string FibonacciTool_Text1 {
            get {
                return ResourceManager.GetString("FibonacciTool_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heikin-Ashi charts are a variation of Japanese candlestick charts that were designed to remove noise from candlesticks and behave much like a moving average..
        /// </summary>
        internal static string HeikinAshi_Text0 {
            get {
                return ResourceManager.GetString("HeikinAshi_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These charts can be used to identify trends, potential reversal points, and other technical analysis patterns..
        /// </summary>
        internal static string HeikinAshi_Text1 {
            get {
                return ResourceManager.GetString("HeikinAshi_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heikin-Ashi charts are a variation of Japanese candlestick charts that were designed to remove noise from candlesticks and behave much like a moving average..
        /// </summary>
        internal static string HeikinAshi_Text2 {
            get {
                return ResourceManager.GetString("HeikinAshi_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A technical indicator is a set of derived data that is calculated by applying one or more formulas to the original set of data. Technical indicators are generally used to forecast the asset&apos;s market direction and generally plotted separately from the original data since the Y-axis scales differ..
        /// </summary>
        internal static string Indicators_Text0 {
            get {
                return ResourceManager.GetString("Indicators_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A technical indicator is a set of derived data that is calculated by applying one or more formulas to the original set of data..
        /// </summary>
        internal static string Indicators_Text1 {
            get {
                return ResourceManager.GetString("Indicators_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Kagi chart displays supply and demand trends using a sequence of linked vertical lines..
        /// </summary>
        internal static string Kagi_Text0 {
            get {
                return ResourceManager.GetString("Kagi_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thickness and direction of the lines vary depending on the price movement.
        ///        If closing prices go in the direction of the previous Kagi line, then that Kagi line is extended.
        ///        However, if the closing price reverses by the preset reversal amount, a new Kagi line is charted in the next column in the opposite direction. Thin lines indicate that the price breaks the previous low (supply) while thick lines indicate that the price breaks the previous high (demand)..
        /// </summary>
        internal static string Kagi_Text1 {
            get {
                return ResourceManager.GetString("Kagi_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Kagi chart displays supply and demand trends using a sequence of linked vertical lines..
        /// </summary>
        internal static string Kagi_Text2 {
            get {
                return ResourceManager.GetString("Kagi_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Line Break or Three Line Break chart uses vertical boxes or lines to illustrate the price changes of an asset or market..
        /// </summary>
        internal static string LineBreak_Text0 {
            get {
                return ResourceManager.GetString("LineBreak_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movements are depicted with box colors and styles;
        ///        movements that continue the trend of the previous box are colored similarly while movements that trend oppositely are indicated with a different color and/or style.
        ///        The opposite trend is only drawn if its value exceeds the extreme value of the previous n number of boxes or lines, which is determined by the newLineBreaks option..
        /// </summary>
        internal static string LineBreak_Text1 {
            get {
                return ResourceManager.GetString("LineBreak_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Line Break or Three Line Break chart uses vertical boxes or lines to illustrate the price changes of an asset or market..
        /// </summary>
        internal static string LineBreak_Text2 {
            get {
                return ResourceManager.GetString("LineBreak_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers display a text area on the FinancialChart that displays the data values based on the mouse cursor&apos;s position on the chart..
        /// </summary>
        internal static string Markers_Text0 {
            get {
                return ResourceManager.GetString("Markers_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers also support optional vertical and horizontal lines to enable a cross-hair effect..
        /// </summary>
        internal static string Markers_Text1 {
            get {
                return ResourceManager.GetString("Markers_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markers display a text area on the FinancialChart that displays the data values based on the mouse cursor&apos;s position on the chart..
        /// </summary>
        internal static string Markers_Text2 {
            get {
                return ResourceManager.GetString("Markers_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string MovingAverages_Day {
            get {
                return ResourceManager.GetString("MovingAverages_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MovingAverages_Settings {
            get {
                return ResourceManager.GetString("MovingAverages_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average trend lines are used to analyze data by creating a series of averages of the original data set..
        /// </summary>
        internal static string MovingAverages_Text0 {
            get {
                return ResourceManager.GetString("MovingAverages_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving average trend lines are used to analyze data by creating a series of averages of the original data set..
        /// </summary>
        internal static string MovingAverages_Text1 {
            get {
                return ResourceManager.GetString("MovingAverages_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlays, like technical indicators, are a set of derived data that is calculated by applying one or more formulas to the original set of data. Overlays are generally used to forecast an asset&apos;s market direction and generally plotted with the original data set since the the Y-axis scales are the same..
        /// </summary>
        internal static string Overlays_Text0 {
            get {
                return ResourceManager.GetString("Overlays_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlays, like technical indicators, are a set of derived data that is calculated by applying one or more formulas to the original set of data..
        /// </summary>
        internal static string Overlays_Text1 {
            get {
                return ResourceManager.GetString("Overlays_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point and Figure chart consists of columns of X&apos;s and O&apos;s that represent filtered price movements.
        ///            X-Columns represent rising prices and O-Columns represent falling prices..
        /// </summary>
        internal static string PointAndFigure_Text0 {
            get {
                return ResourceManager.GetString("PointAndFigure_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point and Figure chart consists of columns of X&apos;s and O&apos;s that represent filtered price movements..
        /// </summary>
        internal static string PointAndFigure_Text1 {
            get {
                return ResourceManager.GetString("PointAndFigure_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RangeSelector allows end users to adjust the FinancialChart&apos;s visible range of data at runtime..
        /// </summary>
        internal static string RangeSelector_Text0 {
            get {
                return ResourceManager.GetString("RangeSelector_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RangeSelector allows end users to adjust the FinancialChart&apos;s visible range of data at runtime..
        /// </summary>
        internal static string RangeSelector_Text1 {
            get {
                return ResourceManager.GetString("RangeSelector_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Line Break or Three Line Break chart uses vertical boxes or lines to illustrate the price changes of an asset or market..
        /// </summary>
        internal static string Renko_Text0 {
            get {
                return ResourceManager.GetString("Renko_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Renko chart uses bricks of uniform size to chart the price movement.
        ///        When a price moves to a greater or lesser value than the preset boxSize option required to draw a new brick, a new brick is drawn in the succeeding column. The change in box color and direction signifies a trend reversal..
        /// </summary>
        internal static string Renko_Text1 {
            get {
                return ResourceManager.GetString("Renko_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Line Break or Three Line Break chart uses vertical boxes or lines to illustrate the price changes of an asset or market..
        /// </summary>
        internal static string Renko_Text2 {
            get {
                return ResourceManager.GetString("Renko_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend lines are used to visualize trends in data and to help analyze the problems of prediction..
        /// </summary>
        internal static string TrendLine_Text0 {
            get {
                return ResourceManager.GetString("TrendLine_Text0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend lines are used to visualize trends in data and to help analyze the problems of prediction..
        /// </summary>
        internal static string TrendLine_Text1 {
            get {
                return ResourceManager.GetString("TrendLine_Text1", resourceCulture);
            }
        }
    }
}
